### PR TITLE
Consider ipads as mobiles

### LINKED ISSUE #3: Consider tablets? iPad etc.
Hi @juliangruber!

Your package is being used at plotly.js, but there seems  to be a trouble detecting tablets, in particular https://github.com/plotly/plotly.js/issues/280. Should this package consider tablet a mobile, or it is better to come up with a separate package `is-tablet`? Thank you!

### PR DESCRIPTION
**Pull request by dy**
Closes #3 
@juliangruber

### CODE REVIEW

**Comment by dy** [comment]
@juliangruber ping

**Comment by juliangruber** [comment]
are there any other opinions on this?

cc'ing people from #3: @vkehayas, @muhilham, @briguyd?

Another option would be to add an option, `{ withTablets: true }`, so we don't make a breaking change?

**Comment by dy** [comment]
The problem is that seems that many existing tablets are already detected as mobiles by this package, and introducing `tablets` option will cause full rewrite of initial regex for mobile-only detection.

This is a blocker for https://github.com/plotly/plotly.js/issues/280 for almost a year now.
I can enable this option for iPads only, but other tablets may need additional patches.

**Comment by dy** [comment]
Ok, following http://detectmobilebrowsers.com/about (this initial regex is taken from there) I can add this option.

**Pull request closed without merging**
