### PR TITLE
perf: cut tableRE, save some extra bytes for bundle

### PR DESCRIPTION
**Pull request by antongolub**
Hi there.

Let's strip a few bytes without sacrificing readability.

### CODE REVIEW

**Comment by antongolub** [comment]
@juliangruber,

Could you take a look?

**Comment by juliangruber** [comment]
Sorry about the delay! I think I wanted to see if anyone else reacted to this.

I'm going to downvote this, as it could introduce bugs, and that's not worth the bytes. This module is pretty stable, and that's worth a lot.

Hope you don't mind! And thank you for your contribution.

**Comment by antongolub** [comment]
Quite clear. I'd just like to point that we chosen this `is-mobile` impl because it is relatively small after minification. 
Size is really important for front-end apps. Anyway, If you change your mind, just let me know, then I'll add more tests to remove doubts about stability.

**Comment by juliangruber** [comment]
If you want to minimize further, I think you could create your own fork, and publish it to a namespace or call it `nano-is-mobile` or something

**Pull request closed without merging**
