### PR TITLE
For compatibility with incominghttpheaders

### PR DESCRIPTION
**Pull request by kaysonwu**

### CODE REVIEW

**Comment by kaysonwu** [comment]
@juliangruber

**Comment by juliangruber** [comment]
can you describe what this fixes?

**Comment by kaysonwu** [comment]
Currently it is not compatible with the [IncomingHttpHeaders](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/http.d.ts#L8) type

**Comment by kaysonwu** [comment]
If I pass a `req` object, it will prompt for type incompatibility

**Comment by juliangruber** [comment]
is this a `req` object from node core?

**Comment by kaysonwu** [comment]
yes

**Comment by kaysonwu** [comment]
[https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/http.d.ts#L8](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/http.d.ts#L8)  The type here is clear enough to allow undefined

**Comment by juliangruber** [comment]
I'm not very experienced with TS, but doesn't this interface also only allow `string | string[]`, as we currently do?

**Comment by juliangruber** [comment]
cc @archmoj @xobotyi @egorovsa @JasonKaz who have worked on the types before

**Comment by xobotyi** [comment]
@juliangruber ill take a look in a few days

**Comment by xobotyi** [comment]
@juliangruber LGTM

**Comment by juliangruber** [comment]
Thanks everyone! https://github.com/juliangruber/is-mobile/releases/tag/v2.2.2

**Pull request merged**
