### PR TITLE
Regex and code improvement

### PR DESCRIPTION
**Pull request by xobotyi**

### CODE REVIEW

**Comment by juliangruber** [comment]
Good catch that this project had mixed code style, I now added `standard` and ran `standard --fix` to enforce consistent code style.

**Comment by juliangruber** [comment]
Can you explain to me why the regexp updates improve them?

**Comment by juliangruber** [comment]
Ok I see, they do make the regexps shorter. If you want to reapply the regexp changes to latest #master (maybe easiest to create a fresh PR), I'm happy to merge them :)

**Comment by xobotyi** [comment]
> Ok I see, they do make the regexps shorter.
Mostly beacue of sets working faster than grouping with alternation (in this case `(4|6) === [46]` so we can compare them)

**Comment by xobotyi** [comment]
@juliangruber updated

**Comment by juliangruber** [comment]
only the regexp changes please, the rest was fine 🙏

**Pull request closed without merging**
