### PR TITLE
handle iOS13 Safari iPad

### PR DESCRIPTION
**Pull request by archmoj**
Fixes https://github.com/juliangruber/is-mobile/issues/17

### CODE REVIEW

**Comment by juliangruber** [comment]
This library currently works on browser _and_ node. While I agree this is the only way to fix it, we then need to separate the logic for node and browser.

**Comment by archmoj** [comment]
@juliangruber thanks very much for the review.
What about adding a new option to the API? 
e.g. `real-tablet`

**Comment by juliangruber** [comment]
I think that's too specific, what about calling it `{ featureDetect: true }`? This way this option will work for any other device that needs this approach.

**Comment by archmoj** [comment]
Something like this?
```js
  var result = opts.tablet ? tabletRE.test(ua) : mobileRE.test(ua)

  if (opts.featureDetect &&
      navigator && navigator.maxTouchPoints > 1 &&
      ua.indexOf('Macintosh') !== -1 &&
      ua.indexOf('Safari') !== -1
    ) result = true
  }
  return result
```

**Comment by juliangruber** [comment]
yeah that should work!

**Comment by juliangruber** [comment]
can you please look at the failing tests?

**Comment by archmoj** [comment]
> can you please look at the failing tests?

Sure. Let me fix that also adding new tests for ipad-pro...

**Comment by juliangruber** [comment]
Thank you so much! Released as 2.2.0 https://github.com/juliangruber/is-mobile/releases/tag/v2.2.0

**Comment by archmoj** [comment]
Brilliant!

**Pull request merged**
